### ISSUE TITLE
gitget jar doesnt run

### ISSUE THREAD

**Issue by slimpyman** [inferno2246/GitGet#1]
downloaded the gitget jar because it seemed useful. have all pertinent java libraries installed, have run many jar applications in the past, and when i run this one, it runs and the process ends and exits.  please fix, this application seems useful and the only one like it ive found.

**Comment by omkarlubal** [comment]
Sorry for replying so late, the jar file is working correctly, open cmd and type 
`java -jar .\GitGet.jar`
You don't need any additional libraries, the jar files contains everything in it already. Hope this helps!
